spring:
  application:
    name: spring-cloud-eureka
  boot:
    admin:
      client:
        url: http://localhost:8084
  zipkin:
    base-url: http://localhost:9411

server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defualtZone: http:${eureka.instance.hostname}:${server.port}/eureka/
