spring:
  application:
    name: spring-cloud-eureka
server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defualtZone: http:${eureka.instance.hostname}:${server.port}/eureka/
