spring:
  application:
    name: service-admin
  boot:
    admin:
      client:
        url: http://localhost:8084
  zipkin:
    base-url: http://localhost:9411

server:
  port: 8762

eureka:
  client:
    service-url:
      defauleZone: http://localhost:8761/eureka/