spring:
  application:
    name: spring-cloud-zuul
  zipkin:
    base-url: http://localhost:9411

server:
  port: 8769

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    api-a:
      path: /api/a/**
      serviceId: client-admin-feign
    api-b:
      path: /api/b/**
      serviceId: client-admin-ribbon

hystrix:
  command:
    client-admin-feign:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
    client-admin-ribbon:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000

client-admin-feign:
  ribbon:
    ReadTimeout : 3000
    ConnectTimeout : 3000

client-admin-ribbon:
  ribbon:
    ReadTimeout : 3000
    ConnectTimeout : 3000